; .devcontainer/supervisord.conf
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
loglevel=info

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd_stdout.log
stderr_logfile=/var/log/supervisor/sshd_stderr.log
